### ISSUE TITLE
Unsupport WebHID browser

### ISSUE THREAD

**Issue by adamrocker** [yoichiro/remap#60]
show error and support message on top page

**Comment by yoichiro** [comment]
@adamrocker You wrote that the error message is shown on top page. But, I guess that it should be shown at opening the `/configure` page, because the top page will become to describe how is this product.

**Comment by adamrocker** [comment]
@yoichiro Agree with you! It is appropriate on 'configure' page.

**Comment by yoichiro** [comment]
Fix at #110 

<img width="748" alt="スクリーンショット 2021-01-11 20 24 10" src="https://user-images.githubusercontent.com/261787/104176812-2bdb3a00-544b-11eb-9c85-a0c481675bd6.png">
